# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gram.Profile'),
        ),
    ]
